language: python
python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
install: 
  - "pip install ."
script: 
  - "python setup.py test"
deploy:
  #TODO
after_success:
  - "pip install python-coveralls"
  - "coveralls"